[package]
name = "cursed_ternary"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.54"
quote = "1.0.26"
# syn = "2.0.12"

[dependencies.syn]
version = "2.0.12"
features = [ "full" ]

[lib]
proc-macro = true

